name: ielts
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.12.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  intl: ^0.20.2
  collection: ^1.19.1
  flutter_svg: ^2.3.0
  sliver_tools: ^0.2.12
  better_player_plus: ^1.3.4
  shimmer: ^3.0.0
  percent_indicator: ^4.2.5
  fl_chart: ^1.2.0
  hexcolor: ^3.1.3
  carousel_slider: ^5.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  assets:
  - assets/images/

  fonts:
  - family: IranSansX-Demi-bold
    fonts:
    - asset: assets/fonts/IRANSansXFaNum-DemiBold.ttf

  - family: IranSansX-black
    fonts:
    - asset: assets/fonts/IRANSansX-Black.ttf

  - family: IranSansX-bold
    fonts:
    - asset: assets/fonts/IRANSansXFaNum-Bold.ttf

  - family: IranSansX-extra-black
    fonts:
    - asset: assets/fonts/IRANSansXFaNum-ExtraBlack.ttf

  - family: IranSansX-extra-bold
    fonts:
    - asset: assets/fonts/IRANSansX-ExtraBold.ttf

  - family: IranSansX-heavy
    fonts:
    - asset: assets/fonts/IRANSansX-Heavy.ttf

  - family: IranSansX-light
    fonts:
    - asset: assets/fonts/IRANSansXFaNum-Light.ttf

  - family: IranSansX-medium
    fonts:
    - asset: assets/fonts/IRANSansXFaNum-Medium.ttf

  - family: IranSansX-regular
    fonts:
    - asset: assets/fonts/IRANSansXFaNum-Regular.ttf

  - family: IranSansX-regular-without-FaNum
    fonts:
    - asset: assets/fonts/IRANSansX-Regular.ttf

  - family: IranSansX-thin
    fonts:
    - asset: assets/fonts/IRANSansX-Thin.ttf

  - family: IranSansX-ultra-light
    fonts:
    - asset: assets/fonts/IRANSansX-UltraLight.ttf

  - family: Gilroy-Regular
    fonts:
    - asset: assets/fonts/GilroyRegular.ttf

  - family: Gilroy-Medium
    fonts:
    - asset: assets/fonts/GilroyMedium.ttf

  - family: Gilroy-Extra-Bold
    fonts:
    - asset: assets/fonts/GilroyExtraBold.ttf
